KS-1-5 complete task
ComradeZgames/KotlinSprint pull request #6
Opened 2024-08-16 06:20 UTC by ComradeZgames

2024-08-16 18:35 UTC, ievetrovdev requested changes

2024-08-16 18:35 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    println("0$hours:$minutes:0$seconds")
Так как это 5 задача ("со звездочкой") не по уровню урока, то предлагаю использовать более элегантное решение). (может потребовать дополнительного ресерча). Для корректного вывода нуля вначале попробуй посмотреть в сторону String.format().

2024-08-16 18:35 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    minutes %= 60
Все окей, но чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-08-16 19:01 UTC, ievetrovdev requested changes

2024-08-16 19:01 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    print(String.format("%02d", seconds))
Почему не сделать все одним print?

2024-08-16 19:03 UTC, ComradeZgames commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    print(String.format("%02d", seconds))
Потому что формат не даёт мне этого сделать, последнее число он пишет прям регуляркой (01:48:02d)

2024-08-17 21:34 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-08-18 03:07 UTC, merged